[project]
name = "data-extractor-from-raw-fmri"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "argparse>=1.4.0",
    "nibabel>=5.3.2",
    "numpy>=2.0.2",
]
